### ISSUE TITLE
[request] bluetooth-6.13

### ISSUE THREAD

**Issue by Smig0l** [jeremyb31/bluetooth-6.11#1]
Hi! Sorry if I post an issue. But wondering if u can make a version compatible with kernel 6.13.

Thanks!

**Comment by jeremyb31** [comment]
What is the issue with the 6.13 kernel?  What is the USB ID for your bluetooth?

**Comment by Smig0l** [comment]
basically the same as [this](https://forums.linuxmint.com/viewtopic.php?p=2608998#p2608998) thread.

kernel -> `6.13.8-200.fc41.x86_64`

lsusb -> `Bus 006 Device 002: ID 2c4e:0115 Mercucys INC Mercusys MA530 Adapter`

tried:
```
sudo apt install git dkms
git clone https://github.com/jeremyb31/bluetooth-6.11.git
sudo dkms add ./bluetooth-6.11
sudo dkms install btusb/4.1
```
i get:
```
sudo dkms install btusb/4.1
Sign command: /lib/modules/6.13.8-200.fc41.x86_64/build/scripts/sign-file
Signing key: /var/lib/dkms/mok.key
Public certificate (MOK): /var/lib/dkms/mok.pub

Cleaning build area... done.
Building module(s)...(bad exit status: 2)
Failed command:
'make' all KVER=6.13.8-200.fc41.x86_64

Error! Bad return status for module build on kernel: 6.13.8-200.fc41.x86_64 (x86_64)
Consult /var/lib/dkms/btusb/4.1/build/make.log for more information.
user@bc250:~$ sudo dkms install btusb/4.2
Sign command: /lib/modules/6.13.8-200.fc41.x86_64/build/scripts/sign-file
Signing key: /var/lib/dkms/mok.key
Public certificate (MOK): /var/lib/dkms/mok.pub


Error! Could not find module source directory.
Directory: /usr/src/btusb-4.2 does not exist.
```

cat `/var/lib/dkms/btusb/4.1/build/make.log`:
```
DKMS (dkms-3.1.6) make.log for btusb/4.1 for kernel 6.13.8-200.fc41.x86_64 (x86_64)
dom 30 mar 2025, 12:16:03, CEST

Cleaning build area
# command: make clean
make -C /lib/modules/6.13.8-200.fc41.x86_64/build M=/var/lib/dkms/btusb/4.1/build clean
make[1]: Entering directory '/usr/src/kernels/6.13.8-200.fc41.x86_64'
make[2]: Entering directory '/var/lib/dkms/btusb/4.1/build'
make[2]: Leaving directory '/var/lib/dkms/btusb/4.1/build'
make[1]: Leaving directory '/usr/src/kernels/6.13.8-200.fc41.x86_64'

# exit code: 0
# elapsed time: 00:00:00
----------------------------------------------------------------

Building module(s)
# command: 'make' all KVER=6.13.8-200.fc41.x86_64
make -C /lib/modules/6.13.8-200.fc41.x86_64/build M=/var/lib/dkms/btusb/4.1/build modules
make[1]: Entering directory '/usr/src/kernels/6.13.8-200.fc41.x86_64'
make[2]: Entering directory '/var/lib/dkms/btusb/4.1/build'
  CC [M]  btusb.o
btusb.c:21:10: fatal error: asm/unaligned.h: No such file or directory
   21 | #include <asm/unaligned.h>
      |          ^~~~~~~~~~~~~~~~~
compilation terminated.
make[4]: *** [/usr/src/kernels/6.13.8-200.fc41.x86_64/scripts/Makefile.build:196: btusb.o] Error 1
make[3]: *** [/usr/src/kernels/6.13.8-200.fc41.x86_64/Makefile:2029: .] Error 2
make[2]: *** [/usr/src/kernels/6.13.8-200.fc41.x86_64/Makefile:263: __sub-make] Error 2
make[2]: Leaving directory '/var/lib/dkms/btusb/4.1/build'
make[1]: *** [Makefile:263: __sub-make] Error 2
make[1]: Leaving directory '/usr/src/kernels/6.13.8-200.fc41.x86_64'
make: *** [Makefile:6: all] Error 2

# exit code: 2
# elapsed time: 00:00:01
----------------------------------------------------------------
```

**Comment by Smig0l** [comment]
Solved by replacing 'asm/unaligned.h' to 'linux/unaligned.h'

**Comment by Smig0l** [comment]
Now it builds and install successfully.
However at reboot I still can't see devices when scanning

**Comment by jeremyb31** [comment]
It needed this patch https://github.com/jeremyb31/bluetooth-6.11/commit/be9096b17cd1e956208296a5e402f4e147383446

**Comment by Smig0l** [comment]
Finally solved. 
I used 'Bluetooth/6.8' repo and replaced 'asm/unaligned.h' with 'linux/unaligned.h'
